name: vines
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - backcall=0.2.0
  - blas=1.0
  - brotli=1.0.9
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=4.4.2
  - expat=2.4.1
  - fftw=3.3.10
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2021.4.0
  - ipykernel=6.4.1
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jpeg=9d
  - jupyter_client=6.1.7
  - jupyter_core=4.9.1
  - kiwisolver=1.3.1
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - llvmlite=0.37.0
  - lz4-c=1.9.3
  - matplotlib=3.5.0
  - matplotlib-base=3.5.0
  - matplotlib-inline=0.1.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - numba=0.54.1
  - numpy=1.20.3
  - numpy-base=1.20.3
  - olefile=0.46
  - openssl=1.1.1l
  - packaging=21.3
  - parso=0.8.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.2.4
  - prompt-toolkit=3.0.8
  - ptyprocess=0.7.0
  - pyfftw=0.12.0
  - pygments=2.7.1
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pyzmq=19.0.2
  - qt=5.9.7
  - readline=8.1.2
  - scipy=1.5.3
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.37.0
  - tbb=2021.4.0
  - tk=8.6.11
  - tornado=6.1
  - traitlets=5.0.5
  - tzdata=2021e
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.5
  - zeromq=4.3.3
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - pickle-mixin==1.0.2
